[".config/base16-shell"]
    type = "git-repo"
    url = "https://github.com/chriskempson/base16-shell.git"
    refreshPeriod = "168h"


[".config/git/external_watchman.pl"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/templates/hooks--fsmonitor-watchman.sample"
    refreshPeriod = "168h"
