[tools]
node = 'lts'
python = ['3.10', '3.11', '3.12']
rust = 'stable'
sccache = { version = "latest", install_env = { RUSTC_WRAPPER = "" }, postinstall = "mise reshim" }

# Python tools
uv = "latest"
"pipx:ipython" = "latest"
"pipx:pgcli" = "latest"
"aqua:duckdb/duckdb" = "latest"

# Dev tools
"aqua:noborus/ov" = "latest"

# Cargo dev tools
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:fd-find" = "latest"
"cargo:tokei" = "latest"
"cargo:starship" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tealdeer" = "latest"
"cargo:xsv" = "latest"
"cargo:hexyl" = "latest"
"cargo:hyperfine" = "latest"
"cargo:git-delta" = "latest"

# Cargo dev tools
"cargo:cargo-watch" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:flamegraph" = "latest"
"cargo:parquet" = { version = "latest", features = "cli" }

[settings]
cache_prune_age = "7d"
jobs = 1

[settings.python]
# Experimental: Disabled for now
#uv_venv_auto = true

[settings.pipx]
uvx = true
