[tools]
node = 'lts'
python = ['3.10', '3.11', '3.12']
rust = {version='stable', cargo_home='~/.config/cargo'}
"cargo:cargo-watch" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:flamegraph" = "latest"
"cargo:parquet" = { version = "latest", features = "cli" }
"cargo:sccache" = "latest"

"pipx:ipython" = "latest"
