[tools]
# Languages
node = 'lts'
python = ['3.10', '3.11', '3.12', '3.13']
rust = 'stable'
terraform = 'latest'
go = "latest"

# Required for all Rust builds
sccache = { version = "latest", install_env = { RUSTC_WRAPPER = "" }, postinstall = "mise reshim" }

# Python tools
uv = "latest"
"pipx:ipython" = "latest"
"pipx:pgcli" = "latest"
"pipx:maturin" = {version = "latest", extras = "zig" }
"aqua:duckdb/duckdb" = "latest"

# Dev tools
"aqua:noborus/ov" = "latest"  # Terminal pager
jq = 'latest'
fzf = 'latest'
pre-commit = "latest"
gh = "latest"
shellcheck = "latest"
yq = "latest"
awscli = "latest"

# Utilities
"ubi:orf/trash" = "latest"

# K8s / Docker stuff
kubectl = "latest"
stern = "latest"
kubectx = "latest"
k9s = "latest"
helm = "latest"
dive = "latest"

# Rust dev tools
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:fd-find" = "latest"
"cargo:tokei" = "latest"
"cargo:starship" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tealdeer" = "latest"
"cargo:xsv" = "latest"
"cargo:hexyl" = "latest"
"cargo:hyperfine" = "latest"
"cargo:git-delta" = "latest"
"cargo:https://github.com/cross-rs/cross" = { version = "branch:main", crate = "cross", locked=false }

# Cargo dev tools
"cargo:cargo-bloat" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:flamegraph" = "latest"
"cargo:parquet" = { version = "latest", features = "cli" }
"cargo:cargo-expand" = "latest"

# Useful utils
glow = "latest"

[settings]
cache_prune_age = "7d"
jobs = 1

[settings.status]
show_tools = false
missing_tools = "never"

[settings.python]
# Experimental: Disabled for now
#uv_venv_auto = true

[settings.pipx]
uvx = true
