[diff]
    command = "git"
    args = ["difftool"]

[merge]
    command = "git"
    args = ["mergetool"]

[edit]
    command = "pycharm"
    args = ["--wait"]

[[textconv]]
pattern = "**/*.plist"
command = "plutil"
args = ["-convert", "xml1", "-o", "-", "-"]
