#[diff]
#    command = "git"
#    args = ["difftool", "--no-index", "{{ .Destination }}", "{{ .Target }}"]

[merge]
    command = "git"
    args = ["mergetool"]

[edit]
    command = "pycharm"
    args = ["--wait"]

[[textconv]]
pattern = "**/*.plist"
command = "/bin/zsh"
args = ["-c", "plutil -convert json -o - - | jq"]
